import test from 'node:test';
import assert from 'node:assert/strict';
import {TwoFingerTransform,screenToWorld,worldToScreen,localToWorld,contains,objectBounds,cropObject,resetCrop,drawObject} from '../dist/geometry.mjs';
import {installGestures} from '../dist/gestures.mjs';
import {MaxTouchInput} from '../dist/play-input.mjs';
import {platforms,validateProject} from '../dist/engine.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('two-finger piece transform keeps midpoint anchored, scales uniformly and rotates',()=>{const o={x:0,y:0,w:100,h:40,inset:4,rotation:0},camera={x:0,y:0,z:1};const t=new TwoFingerTransform(o,{x:10,y:20},{x:90,y:20},'object',camera);t.update({x:80,y:-50},{x:80,y:110});near(o.w,200);near(o.h,80);near(o.rotation,90);near(o.inset,8);near(o.x+o.w/2,80);near(o.y+o.h/2,30);assert.ok(contains(o,{x:80,y:30}));assert.ok(!contains(o,{x:0,y:30}))});
test('rotated camera keeps content under the pinch midpoint, including scale clamps',()=>{const c={x:3,y:-20,z:2,rotation:.4};const a={x:20,y:80},b={x:160,y:80},anchor=screenToWorld({x:90,y:80},c);const t=new TwoFingerTransform(c,a,b,'camera');t.update({x:100,y:-800},{x:100,y:900});near(c.z,12);const screen=worldToScreen(anchor,c);near(screen.x,100);near(screen.y,50);for(const p of [{x:3,y:99},{x:-400,y:12}]){const q=screenToWorld(worldToScreen(p,c),c);near(q.x,p.x);near(q.y,p.y)}});
test('crossing ±180 degrees and near-coincident fingers do not jump or produce invalid values',()=>{const o={x:0,y:0,w:10,h:20,inset:0},c={x:0,y:0,z:1};const at=d=>({x:Math.cos(d*Math.PI/180)*50,y:Math.sin(d*Math.PI/180)*50});const t=new TwoFingerTransform(o,{x:0,y:0},at(179),'object',c);t.update({x:0,y:0},at(-179));near(o.rotation,0);t.update({x:0,y:0},{x:0,y:0});const before={...o};t.update({x:0,y:0},{x:20,y:0});assert.deepEqual(o,before);t.update({x:0,y:0},{x:40,y:0});assert.ok(Number.isFinite(o.x)&&o.w>0)});
function harness({crop=false,locked=false}={}){const listeners={},canvas={addEventListener:(k,f)=>listeners[k]=f,getBoundingClientRect:()=>({left:0,top:0}),focus(){},setPointerCapture(){},releasePointerCapture(){}};let state={name:'test',spawn:{x:-999,y:0},assets:[],objects:[{id:'piece',x:20,y:20,w:80,h:60,inset:0,rotation:0,kind:'solid',locked}]},selected='piece',g,menu=null,cropped=null,commits=[],camera={x:0,y:0,z:1,rotation:0};const controller=installGestures(canvas,{get:()=>({state,camera,tool:'select',grid:4,playing:false,keys:new Set(),selected:state.objects.find(o=>o.id===selected),crop}),snapshot:()=>structuredClone(state),rollback:b=>state=b,preview:v=>g=v,hover(){},select:id=>selected=id,closePanels(){},refresh(){},viewChanged(){},context:(id,p)=>menu={id,p},crop:r=>cropped=r,commit:b=>commits.push(b),addBlock(){throw Error('Unexpected block')},place(){throw Error('Unexpected placement')}});const send=(type,id,x,y)=>listeners[type]({pointerId:id,clientX:x,clientY:y,pointerType:'touch',button:0,preventDefault(){}});return{send,controller,state:()=>state,commits,camera,gesture:()=>g,menu:()=>menu,cropped:()=>cropped}}
test('finger add/remove and third-finger replacement preserve one gesture and one undo',()=>{const h=harness(),s=h.send;s('pointerdown',1,30,40);s('pointermove',1,35,40);const moved={...h.state().objects[0]};s('pointerdown',2,85,40);assert.deepEqual(h.state().objects[0],moved);s('pointermove',2,105,60);s('pointerdown',3,150,70);const before={...h.state().objects[0]};s('pointerup',2,105,60);assert.deepEqual(h.state().objects[0],before);s('pointermove',3,160,80);s('pointerup',3,160,80);const one={...h.state().objects[0]};s('pointermove',1,35,40);assert.deepEqual(h.state().objects[0],one);s('pointermove',1,40,45);near(h.state().objects[0].x,one.x+5);s('pointerup',1,40,45);assert.equal(h.commits.length,1);assert.equal(h.commits[0].objects[0].x,20)});
test('cancel and lost capture restore the piece and clear every pointer',()=>{for(const event of ['pointercancel','lostpointercapture']){const h=harness(),original=structuredClone(h.state());h.send('pointerdown',1,30,40);h.send('pointerdown',2,85,40);h.send('pointermove',2,120,70);h.send(event,1,30,40);assert.deepEqual(h.state(),original);assert.equal(h.controller.active(),false);h.send('pointerup',2,120,70);assert.equal(h.commits.length,0);h.send('pointerdown',4,30,40);h.send('pointermove',4,50,40);h.send('pointerup',4,50,40);assert.equal(h.commits.length,1)}});
test('rotated collision follows the surface and survives project validation',()=>{const o={id:'a',asset:null,name:'Slope',x:0,y:0,w:100,h:10,rotation:30,inset:0,kind:'platform',flip:false},ps=platforms([o]);assert.ok(ps.length>80);assert.ok(ps.at(-1).y>ps[0].y+40);const b=objectBounds(o);assert.ok(b.h>50);const p=validateProject({format:'max-level-studio',version:1,name:'Slope',spawn:{x:0,y:0},assets:[],objects:[o]});near(p.objects[0].rotation,30)});
test('Max touch controls match deadzone, variable steering, swipe jump and quick dodge',()=>{const c=new MaxTouchInput(),keys=new Set();c.down(1,100,200,0);c.move(1,110,200);assert.equal(c.read(keys).axis,0);c.move(1,144,200);const moving=c.read(keys);assert.equal(moving.axis,1);near(moving.top,68);c.move(1,176,200);near(c.read(keys).top,88);c.move(1,176,170);assert.equal(c.read(keys).jumpPressed,true);assert.equal(c.read(keys).jumpPressed,false);c.move(1,176,160);assert.equal(c.read(keys).jumpPressed,false);c.move(1,176,180);c.move(1,176,150);assert.equal(c.read(keys).jumpPressed,true);c.reset();c.down(2,50,100,0);c.move(2,110,100);c.up(2,110,100,100);assert.equal(c.read(keys).dodge,1);c.reset();c.down(3,50,100,0);c.move(3,110,100);c.up(3,110,100,100,true);assert.equal(c.read(keys).dodge,0)});
test('stationary two-finger tap exits, running and interrupted touches never exit',()=>{const c=new MaxTouchInput();c.down(1,20,20,0);c.down(2,80,20,50);assert.equal(c.up(1,20,20,100),false);assert.equal(c.up(2,80,20,120),true);c.down(1,20,20,500);c.move(1,60,20);c.down(2,80,20,530);c.up(2,80,20,550);assert.equal(c.up(1,60,20,570),false)});

test('one-finger resize is proportional; touch pinch can stretch one axis',()=>{const h=harness();h.send('pointerdown',1,100,80);h.send('pointermove',1,140,80);h.send('pointerup',1,140,80);near(h.state().objects[0].w/h.state().objects[0].h,80/60);const o={x:0,y:0,w:100,h:40,inset:2,rotation:0},t=new TwoFingerTransform(o,{x:10,y:20},{x:90,y:20},'object',{x:0,y:0,z:1},{free:true});t.update({x:-30,y:20},{x:130,y:20});near(o.w,200);near(o.h,40)});
test('long hold opens the piece menu without moving it; locked pieces cannot move',async()=>{const h=harness({locked:true}),original=structuredClone(h.state());h.send('pointerdown',1,30,40);await new Promise(r=>setTimeout(r,480));assert.equal(h.menu().id,'piece');assert.deepEqual(h.state(),original);assert.equal(h.controller.active(),false);h.send('pointerdown',2,30,40);h.send('pointermove',2,60,60);h.send('pointerup',2,60,60);assert.deepEqual(h.state(),original);assert.equal(h.commits.length,0)});
test('crop drag tracks a bounded local rectangle',()=>{const h=harness({crop:true});h.send('pointerdown',1,30,30);h.send('pointermove',1,180,65);h.send('pointerup',1,180,65);assert.deepEqual(h.cropped(),{x:10,y:10,w:70,h:35})});
test('cropping and reset preserve rotated, flipped source placement; rendering uses crop and opacity',()=>{for(const flip of [false,true]){const o={x:4,y:20,w:100,h:80,inset:0,rotation:37,flip,opacity:.4},old={...o};const expected=localToWorld({x:40,y:35},o);cropObject(o,{x:20,y:10,w:40,h:50});near(o.x+o.w/2,expected.x);near(o.y+o.h/2,expected.y);near(o.crop.x,flip?.4:.2);const calls=[],ctx={save(){},restore(){},translate(){},rotate(){},scale(){},drawImage(...args){calls.push(args)}};const image={width:200,height:160};drawObject(ctx,o,image);near(ctx.globalAlpha,.4);near(calls[0][1],flip?80:40);near(calls[0][2],20);near(calls[0][3],80);near(calls[0][4],100);resetCrop(o);for(const key of ['x','y','w','h','rotation'])near(o[key],old[key]);assert.equal(o.crop,null)}});
