import test from 'node:test';
import assert from 'node:assert/strict';
import {installNumberScrub} from '../dist/number-scrub.mjs';
import {installAssetTray} from '../dist/asset-tray.mjs';
import {pixelTiles,paintPixelLayer} from '../dist/pixel-view.mjs';
import {TwoFingerTransform,snapObject,screenToWorld,worldToScreen} from '../dist/geometry.mjs';
class Field{
 constructor(){this.value='20';this.min='0';this.max='100';this.step='1';this.handlers={};this.classList={toggle(){}};this.focused=false}
 setAttribute(){}addEventListener(type,fn){this.handlers[type]=fn}setPointerCapture(){}releasePointerCapture(){}focus(){this.focused=true}blur(){this.focused=false}select(){}
 send(type,x,y=0,id=1){this.handlers[type]?.({pointerId:id,clientX:x,clientY:y,pointerType:'touch',button:0,preventDefault(){},stopPropagation(){}})}
}
test('number scrubbing previews, commits once, clamps, reverses immediately and cancels safely',()=>{const f=new Field(),previews=[];let commits=0,cancels=0;installNumberScrub([f],{preview:(_,n)=>{previews.push(n)},commit:()=>commits++,cancel:()=>cancels++});f.send('pointerdown',0);f.send('pointerup',2);assert.equal(f.focused,true);assert.equal(commits,0);f.send('pointerdown',0);f.send('pointermove',40);assert.equal(f.value,'30');assert.equal(f.focused,false);f.send('pointermove',1000);assert.equal(f.value,'100');f.send('pointermove',996);assert.equal(f.value,'99');f.send('pointerup',996);assert.equal(commits,1);f.send('pointerdown',0);f.send('pointermove',-40);f.send('pointercancel',-40);assert.equal(f.value,'99');assert.equal(cancels,1);f.disabled=true;f.send('pointerdown',0);f.send('pointermove',100);assert.equal(f.value,'99')});
test('angle scrub uses five degree steps and the tray snaps to one, two or four rows',()=>{const angle=new Field();angle.step='5';installNumberScrub([angle]);angle.send('pointerdown',0);angle.send('pointermove',8);angle.send('pointerup',8);assert.equal(angle.value,'30');const h=new Field();let rows=1,preview;installAssetTray(h,{rows:()=>rows,height:n=>28+72*n,preview:n=>preview=n,setRows:n=>rows=n});h.send('pointerdown',0,400);h.send('pointermove',0,325);assert.equal(preview,175);h.send('pointerup',0,325);assert.equal(rows,2);h.send('pointerdown',0,400);h.send('pointermove',0,240);h.send('pointerup',0,240);assert.equal(rows,4);h.send('pointerdown',0,100);h.send('pointermove',0,500);h.send('pointercancel',0,500);assert.equal(rows,4);h.send('pointerdown',0,100);h.send('pointermove',0,500);h.send('pointerup',0,500);assert.equal(rows,1)});
test('camera pinch stays upright, piece rotation steps by five, and final placement snaps to pixels',()=>{const c={x:-3,y:10,z:2,rotation:0},anchor=screenToWorld({x:50,y:20},c);const t=new TwoFingerTransform(c,{x:10,y:20},{x:90,y:20},'camera');t.update({x:50,y:-60},{x:50,y:100});assert.equal(c.rotation,0);assert.equal(c.z,4);assert.deepEqual(worldToScreen(anchor,c),{x:50,y:20});const o={x:.3,y:3.8,w:30.2,h:20.6,rotation:13,inset:.2};snapObject(o,4,{dimensions:true});assert.deepEqual([o.x,o.y,o.w,o.h,o.rotation],[0,4,30,21,15])});
test('pixel renderer keeps every tile on the same unit grid and bounds its buffer',()=>{const view={x:-.3,y:5.2,w:2200.4,h:1400.8},tiles=[...pixelTiles(view)];assert.equal(tiles.length,6);for(const t of tiles)for(const k of ['x','y','w','h'])assert.ok(Number.isInteger(t[k]));assert.ok(tiles.every(t=>t.w<=1024&&t.h<=1024));assert.equal(tiles.reduce((n,t)=>n+t.w*t.h,0),(Math.ceil(view.x+view.w)-Math.floor(view.x))*(Math.ceil(view.y+view.h)-Math.floor(view.y)));const context={setTransform(){},clearRect(){},translate(){}},buffer={getContext:()=>context},copies=[],target={drawImage:(b,x,y)=>copies.push({x,y,w:b.width,h:b.height})};paintPixelLayer(target,buffer,view,()=>{});assert.deepEqual(copies,tiles);assert.equal(target.imageSmoothingEnabled,false);assert.equal(context.imageSmoothingEnabled,false)});
